/**
 * Created by Calvin Huang on 2/23/17.
 */

export const OPEN_SIDE_DRAWER = 'OPEN_SIDE_DRAWER';
export const CLOSE_SIDE_DRAWER = 'CLOSE_SIDE_DRAWER';

export const HIDE_NAVIGATION_BAR = 'HIDE_NAVIGATION_BAR';
export const SHOW_NAVIGATION_BAR = 'SHOW_NAVIGATION_BAR';

export const REQUESTED_WAYBILLS = 'REQUESTED_WAYBILLS';
export const RECEIVED_WAYBILLS_SUCCESS = 'RECEIVED_WAYBILLS_SUCCESS';
export const RECEIVED_WAYBILLS_FAILED = 'RECEIVED_WAYBILLS_FAILED';

export const START_REFRESHING_WAYBILLS = 'START_REFRESHING_WAYBILLS';
export const REFRESH_WAYBILLS_SUCCESS = 'REFRESH_WAYBILLS_SUCCESS';
export const REFRESH_WAYBILLS_FAILED = 'REFRESH_WAYBILLS_FAILED';

export const ADD_WAYBILL = 'ADD_WAYBILL';
export const ADD_WAYBILL_SUCCESS = 'ADD_WAYBILL_SUCCESS';
export const ADD_WAYBILL_FAILED = 'ADD_WAYBILL_FAILED';

export const URGENT_WAYBILL = 'URGENT_WAYBILL';

export const CALCULATE_FEE = 'CALCULATE_FEE';
export const CALCULATE_FEE_DONE = 'CALCULATE_FEE_DONE';

export const FETCH_FAQS = 'FETCH_FAQS';
export const FETCH_FAQS_SUCCESS = 'FETCH_FAQS_SUCCESS';
export const FETCH_FAQS_FAILED = 'FETCH_FAQ_FAILED';

export const REFRESH_FAQS = 'REFRESH_FAQS';
export const REFRESH_FAQS_SUCCESS = 'REFRESH_FAQS_SUCCESS';

export const FETCH_FAQ = 'FETCH_FAQ';
export const FETCH_FAQ_SUCCESS = 'FETCH_FAQ_SUCCESS';
export const FETCH_FAQ_FAILED = 'FETCH_FAQ_FAILED';

export const CHECK_USER_SIGNED_IN = 'CHECK_USER_SIGNED_IN';
export const USER_SIGN_IN = 'USER_SIGN_IN';
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export const USER_SIGN_IN_FAILED = 'USER_SIGN_IN_FAILED';

export const USER_SIGN_OUT = 'USER_SIGN_OUT';
export const USER_SIGN_OUT_SUCCESS = 'USER_SIGN_OUT_SUCCESS';

export const SHOW_USER_QRCODE = 'SHOW_USER_QRCODE';
export const HIDE_USER_QRCODE = 'HIDE_USER_QRCODE';

export const GENERAL_REQUEST = 'GENERAL_REQUEST';
export const GENERAL_REQUEST_SUCCESS = 'GENERAL_REQUEST_SUCCESS';
export const GENERAL_REQUEST_FAILED = 'URGENT_WAYBILL_FAILED';
