/**
 * Created by Calvin Huang on 2/23/17.
 */

export const OPEN_SIDE_DRAWER = 'OPEN_SIDE_DRAWER';
export const CLOSE_SIDE_DRAWER = 'CLOSE_SIDE_DRAWER';

export const HIDE_NAVIGATION_BAR = 'HIDE_NAVIGATION_BAR';
export const SHOW_NAVIGATION_BAR = 'SHOW_NAVIGATION_BAR';

export const REQUESTED_WAYBILLS = 'REQUESTED_WAYBILLS';
export const RECEIVED_WAYBILLS_SUCCESS = 'RECEIVED_WAYBILLS_SUCCESS';
export const RECEIVED_WAYBILLS_FAILED = 'RECEIVED_WAYBILLS_FAILED';
