/**
 * Created by Calvin Huang on 2/23/17.
 */

export const FETCH_CURRENT_VERSION_INFO = 'FETCH_CURRENT_VERSION_INFO';
export const SHOW_VERSION_OUTDATED_HINT = 'SHOW_VERSION_OUTDATED_HINT';
export const HIDE_VERSION_OUTDATED_HINT = 'HIDE_VERSION_OUTDATED_HINT';

export const OPEN_SIDE_DRAWER = 'OPEN_SIDE_DRAWER';
export const CLOSE_SIDE_DRAWER = 'CLOSE_SIDE_DRAWER';

export const NAVIGATION_ITEM_SELECTED = 'NAVIGATION_ITEM_SELECTED';

export const FETCH_BADGES = 'FETCH_BADGES';
export const REMOVE_BADGE = 'REMOVE_BADGE';
export const UPDATE_BADGES = 'UPDATE_BADGES';

export const HIDE_NAVIGATION_BAR = 'HIDE_NAVIGATION_BAR';
export const SHOW_NAVIGATION_BAR = 'SHOW_NAVIGATION_BAR';

export const REQUESTED_WAYBILLS = 'REQUESTED_WAYBILLS';
export const RECEIVED_WAYBILLS_SUCCESS = 'RECEIVED_WAYBILLS_SUCCESS';
export const RECEIVED_WAYBILLS_FAILED = 'RECEIVED_WAYBILLS_FAILED';

export const START_REFRESHING_WAYBILLS = 'START_REFRESHING_WAYBILLS';
export const REFRESH_WAYBILLS_SUCCESS = 'REFRESH_WAYBILLS_SUCCESS';
export const REFRESH_WAYBILLS_FAILED = 'REFRESH_WAYBILLS_FAILED';

export const FETCH_CONTACT_INFO = 'FETCH_CONTACT_INFO';
export const FETCH_CONTACT_INFO_SUCCESS = 'FETCH_CONTACT_INFO_SUCCESS';
export const FETCH_CONTACT_INFO_FAILED = 'FETCH_CONTACT_INFO_FAILED';

export const ADD_WAYBILL = 'ADD_WAYBILL';
export const ADD_WAYBILL_SUCCESS = 'ADD_WAYBILL_SUCCESS';
export const ADD_WAYBILL_FAILED = 'ADD_WAYBILL_FAILED';

export const DELETE_WAYBILL = 'DELETE_WAYBILL';

export const URGENT_WAYBILL = 'URGENT_WAYBILL';

export const CALCULATE_FEE = 'CALCULATE_FEE';
export const CALCULATE_FEE_DONE = 'CALCULATE_FEE_DONE';

export const FETCH_DELIVERY_INFO_LIST = 'FETCH_DELIVERY_INFO_LIST';
export const FETCH_DELIVERY_INFO_LIST_SUCCESS = 'FETCH_DELIVERY_INFO_LIST_SUCCESS';
export const FETCH_DELIVERY_INFO_LIST_FAILED = 'FETCH_DELIVERY_INFO_LIST_FAILED';

export const REFRESH_DELIVERY_INFO_LIST = 'REFRESH_DELIVERY_INFO_LIST';
export const REFRESH_DELIVERY_INFO_LIST_SUCCESS = 'REFRESH_DELIVERY_INFO_LIST_SUCCESS';

export const FETCH_DELIVERY_INFO = 'FETCH_DELIVERY_INFO';
export const FETCH_DELIVERY_INFO_SUCCESS = 'FETCH_DELIVERY_INFO_SUCCESS';
export const FETCH_DELIVERY_INFO_FAILED = 'FETCH_DELIVERY_INFO_FAILED';

export const FETCH_SERVICE_STORES = 'FETCH_SERVICE_STORES';
export const FETCH_SERVICE_STORES_SUCCESS = 'FETCH_SERVICE_STORES_SUCCESS';
export const FETCH_SERVICE_STORES_FAILED = 'FETCH_SERVICE_STORES_FAILED';

export const REFRESH_SERVICE_STORES = 'REFRESH_SERVICE_STORES';
export const REFRESH_SERVICE_STORES_SUCCESS = 'REFRESH_SERVICE_STORES_SUCCESS';

export const FETCH_SERVICE_STORE = 'FETCH_SERVICE_STORE';
export const FETCH_SERVICE_STORE_SUCCESS = 'FETCH_SERVICE_STORE_SUCCESS';
export const FETCH_SERVICE_STORE_FAILED = 'FETCH_SERVICE_STORE_FAILED';

export const FETCH_BULLETIN_BOARD = 'FETCH_BULLETIN_BOARD';
export const FETCH_BULLETIN_BOARD_SUCCESS = 'FETCH_BULLETIN_BOARD_SUCCESS';
export const FETCH_BULLETIN_BOARD_FAILED = 'FETCH_BULLETIN_BOARD_FAILED';

export const START_BULLETIN_BOARD_SEARCH_MODE = 'START_BULLETIN_BOARD_SEARCH_MODE';
export const STOP_BULLETIN_BOARD_SEARCH_MODE = 'STOP_BULLETIN_BOARD_SEARCH_MODE';
export const SEARCH_BULLETIN_BOARD = 'SEARCH_BULLETIN_BOARD';

export const REFRESH_BULLETIN_BOARD = 'REFRESH_BULLETIN_BOARD';
export const REFRESH_BULLETIN_BOARD_SUCCESS = 'REFRESH_BULLETIN_BOARD_SUCCESS';
export const REFRESH_BULLETIN_BOARD_FAILED = 'REFRESH_BULLETIN_BOARD_FAILED';

export const FETCH_BULLETIN = 'FETCH_BULLETIN';
export const FETCH_BULLETIN_SUCCESS = 'FETCH_BULLETIN_SUCCESS';
export const FETCH_BULLETIN_FAILED = 'FETCH_BULLETIN_FAILED';

export const FETCH_FAQS = 'FETCH_FAQS';
export const FETCH_FAQS_SUCCESS = 'FETCH_FAQS_SUCCESS';
export const FETCH_FAQS_FAILED = 'FETCH_FAQS_FAILED';

export const REFRESH_FAQS = 'REFRESH_FAQS';
export const REFRESH_FAQS_SUCCESS = 'REFRESH_FAQS_SUCCESS';

export const FETCH_FAQ = 'FETCH_FAQ';
export const FETCH_FAQ_SUCCESS = 'FETCH_FAQ_SUCCESS';
export const FETCH_FAQ_FAILED = 'FETCH_FAQ_FAILED';

export const CHECK_USER_SIGNED_IN = 'CHECK_USER_SIGNED_IN';
export const USER_SIGN_IN = 'USER_SIGN_IN';
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export const USER_SIGN_IN_FAILED = 'USER_SIGN_IN_FAILED';

export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';

export const USER_CONFIRM_REGISTRATION_CODE = 'USER_CONFIRM_REGISTRATION_CODE';

export const USER_RESEND_CONFIRM_CODE = 'USER_RESEND_CONFIRM_CODE';
export const USER_RESEND_CONFIRM_CODE_SUCCESS = 'USER_RESEND_CONFIRM_CODE_SUCCESS';
export const USER_RESEND_CONFIRM_CODE_FAILED = 'USER_RESEND_CONFIRM_CODE_FAILED';

export const USER_REQUEST_RESET_PASSWORD = 'USER_REQUEST_RESET_PASSWORD';
export const USER_REQUEST_RESET_PASSWORD_SUCCESS = 'USER_REQUEST_RESET_PASSWORD_SUCCESS';

export const USER_CONFIRM_RESET_PASSWORD_CODE = 'USER_CONFIRM_RESET_PASSWORD_CODE';

export const USER_RESEND_RESET_PASSWORD_CONFIRM_CODE = 'USER_RESEND_RESET_PASSWORD_CONFIRM_CODE';
export const USER_RESEND_RESET_PASSWORD_CONFIRM_CODE_SUCCESS = 'USER_RESEND_RESET_PASSWORD_CONFIRM_CODE_SUCCESS';
export const USER_RESEND_RESET_PASSWORD_CONFIRM_CODE_FAILED = 'USER_RESEND_RESET_PASSWORD_CONFIRM_CODE_FAILED';

export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const USER_INFO_UPDATED = 'USER_INFO_UPDATED';

export const USER_SIGN_OUT = 'USER_SIGN_OUT';
export const USER_SIGN_OUT_SUCCESS = 'USER_SIGN_OUT_SUCCESS';

export const SHOW_USER_QRCODE = 'SHOW_USER_QRCODE';
export const HIDE_USER_QRCODE = 'HIDE_USER_QRCODE';

export const CHECK_FCM_SUBSCRIBE_STATUS = 'CHECK_FCM_SUBSCRIBE_STATUS';
export const FCM_SUBSCRIBE_STATUS_RESULT = 'FCM_SUBSCRIBE_STATUS_RESULT';
export const FCM_SUBSCRIBE_STATE_UPDATED = 'FCM_SUBSCRIBE_STATE_UPDATED';

export const GENERAL_REQUEST = 'GENERAL_REQUEST';
export const GENERAL_REQUEST_SUCCESS = 'GENERAL_REQUEST_SUCCESS';
export const GENERAL_REQUEST_FAILED = 'URGENT_WAYBILL_FAILED';
export const RESET_GENERAL_REQUEST = 'RESET_GENERAL_REQUEST';
